# =============================================================================
# GitLab CI/CD Pipeline - MS-DISTRIBUTION
# Construye y sube imagen Docker a DockerHub
# =============================================================================

stages:
  - build
  - test
  - docker-build

variables:
  DOCKER_IMAGE_NAME: 'ronaldinhoccencho/ms-distribution'
  DOCKER_TAG: 'latest'
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

# Cache para optimizar builds
cache:
  paths:
    - .m2/repository/
    - target/

# =============================================================================
# STAGE 1: Build
# =============================================================================
maven-build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17-alpine
  script:
    - echo "🚀 Iniciando build del MS-users..."
    - mvn --version
    - java -version
    - echo "📦 Descargando dependencias..."
    - mvn dependency:resolve -B -q
    - echo "🔨 Compilando proyecto..."
    - mvn clean compile -B -q
    - echo "📋 Generando JAR..."
    - mvn package -DskipTests -B -q
    - ls -la target/
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  only:
    - main
    - develop
    - merge_requests

# =============================================================================
# STAGE 3: Docker Build & Push
# =============================================================================
docker-build-push:
  stage: docker-build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: '/certs'
  before_script:
    - echo "🐳 Configurando Docker..."
    - docker info
    - echo "🔑 Autenticando con DockerHub..."
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - echo "🏗 Construyendo imagen Docker del MS-users..."
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
    - docker build -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - echo "📤 Subiendo imagen a DockerHub..."
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - echo "✅ Imagen MS-users subida exitosamente:"
    - echo "   - $DOCKER_IMAGE_NAME:$DOCKER_TAG"
    - echo "   - $DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  after_script:
    - docker logout
  dependencies:
    - maven-build
  only:
    - main
    - develop
# =============================================================================
# ✅ Pipeline completo hasta subir imagen a DockerHub
# =============================================================================
# =============================================================================
# Variables de entorno requeridas en GitLab:
# DOCKERHUB_USERNAME: isaelfatamadev
# DOCKERHUB_TOKEN: [CONFIGURAR EN GITLAB SECRETS]
# =============================================================================